name: maven test devops

on:
  push:
    branch: [master]

jobs:
  build:
    run on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: setup-java
      uses: actions/setup-java@v1
      with:
        java-version: 14
