name: maven test devops

on:
  push:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: setup-java
      uses: actions/setup-java@v1
      with:
        java-version: 14
  
  build-project:
    name: test-build
    runs-on: ubuntu-latest

    steps:
      - name: test command
        run: echo 'hello world'
